# Generated by Django 4.1.5 on 2023-08-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0003_remove_post_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default='123-456-7890', max_length=15),
        ),
    ]
