# Generated by Django 4.1.5 on 2023-08-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0005_post_image_alter_image_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
