# Generated by Django 4.1.5 on 2023-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0006_rename_author_post_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='username', max_length=40),
        ),
    ]
