# Generated by Django 4.1.5 on 2023-08-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0007_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fav_by',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
