# Generated by Django 4.1.5 on 2023-08-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0010_alter_image_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
