# Generated by Django 4.1.5 on 2023-08-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0013_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
