# Generated by Django 4.1.5 on 2023-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderHands', '0017_alter_image_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(default='https://res.c', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://res.c', max_length=2000),
        ),
    ]
